### ISSUE TITLE
Routine day count

### ISSUE THREAD

**Issue by iamjomz** [Jefit/Android-Bug-Report#13]
On Android version 9.12, search results for routines show day counts off by one. Tapping them shows the correct number. See photo for example 1  day/week routine showing up as 0.
![wp1](https://cloud.githubusercontent.com/assets/16845665/14712560/321503e2-0810-11e6-8622-9d2d2e2f44d0.png)
![wp2](https://cloud.githubusercontent.com/assets/16845665/14712645/96811780-0810-11e6-9c9e-3873f74d9c4b.png)

**Comment by davidpao** [comment]
Fixed
